// SitePilot AI — SQLite Schema (local development / testing)
// ---------------------------------------------------------------------------
// Mirror of the PostgreSQL schema (packages/db/src/schema) for the SQLite
// dialect. Same table names, same column names, so application code that
// imports `schema` from "@sitepilot/db" works against both dialects.
//
// Type mapping vs PostgreSQL:
//   uuid / varchar / text  -> text
//   jsonb                  -> text({ mode: "json" })   (auto JSON stringify/parse)
//   timestamp (tz)         -> integer({ mode: "timestamp_ms" })  (unix epoch ms)
//   decimal / numeric      -> real
//   smallint / integer     -> integer
//   boolean                -> integer({ mode: "boolean" })
//   uuid[] (arrays)        -> text({ mode: "json" }).$type<string[]>()
//
// UUID primary keys are generated by $defaultFn (crypto.randomUUID) because
// SQLite has no built-in gen_random_uuid().
// ---------------------------------------------------------------------------
import { sqliteTable, text, integer, real, index, uniqueIndex } from "drizzle-orm/sqlite-core";
import { randomUUID } from "node:crypto";

export const uuid = (name: string) => text(name);
export const uid = () => text("id").primaryKey().$defaultFn(() => randomUUID());
export const jsonCol = <T>(name: string, fallback: T) => text(name, { mode: "json" }).$type<T>().default(fallback);
export const ts = (name: string) => integer(name, { mode: "timestamp_ms" });
export const tsNow = (name: string) => integer(name, { mode: "timestamp_ms" }).notNull().defaultNow();
export const money = (name: string) => real(name);
export const bool = (name: string) => integer(name, { mode: "boolean" });

// ---- 3.3.1: organizations ----
export const organizations = sqliteTable(
  "organizations",
  {
    id: uid(),
    name: text("name").notNull(),
    slug: text("slug").notNull().unique(),
    logoUrl: text("logo_url"),
    website: text("website"),
    phone: text("phone"),
    email: text("email"),
    addressLine1: text("address_line1"),
    addressLine2: text("address_line2"),
    city: text("city"),
    state: text("state"),
    postalCode: text("postal_code"),
    country: text("country").default("US"),
    timezone: text("timezone").default("UTC"),
    currency: text("currency").default("USD"),
    businessHours: jsonCol<Record<string, unknown> | null>("business_hours", null as unknown as Record<string, unknown>),
    settings: jsonCol<Record<string, unknown>>("settings", {}),
    customFields: jsonCol<unknown[]>("custom_fields", []),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [index("idx_orgs_slug").on(table.slug)],
);

// ---- 3.3.2: users ----
export const users = sqliteTable(
  "users",
  {
    id: uid(),
    orgId: uuid("org_id").references(() => organizations.id),
    email: text("email").notNull(),
    emailVerified: bool("email_verified").default(false),
    passwordHash: text("password_hash").notNull(),
    firstName: text("first_name").notNull(),
    lastName: text("last_name").notNull(),
    phone: text("phone"),
    avatarUrl: text("avatar_url"),
    role: text("role").notNull().default("business_owner"),
    permissions: jsonCol<string[]>("permissions", []),
    isActive: bool("is_active").default(true),
    lastLoginAt: ts("last_login_at"),
    refreshToken: text("refresh_token"),
    refreshTokenExpiresAt: ts("refresh_token_expires_at"),
    settings: jsonCol<Record<string, unknown>>("settings", {}),
    deletedAt: ts("deleted_at"),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    uniqueIndex("idx_users_email_org").on(table.orgId, table.email),
    index("idx_users_org").on(table.orgId),
    index("idx_users_refresh_token").on(table.refreshToken),
  ],
);

// ---- 3.3.3: customers ----
export const customers = sqliteTable(
  "customers",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    firstName: text("first_name").notNull(),
    lastName: text("last_name").notNull(),
    company: text("company"),
    email: text("email"),
    phone: text("phone"),
    phoneAlt: text("phone_alt"),
    addressLine1: text("address_line1"),
    addressLine2: text("address_line2"),
    city: text("city"),
    state: text("state"),
    postalCode: text("postal_code"),
    country: text("country"),
    latitude: real("latitude"),
    longitude: real("longitude"),
    source: text("source"),
    tags: jsonCol<string[]>("tags", []),
    notes: text("notes"),
    customFields: jsonCol<Record<string, unknown>>("custom_fields", {}),
    lifetimeValue: money("lifetime_value").default(0),
    totalJobs: integer("total_jobs").default(0),
    lastJobAt: ts("last_job_at"),
    stripeCustomerId: text("stripe_customer_id"),
    portalEnabled: bool("portal_enabled").default(false),
    deletedAt: ts("deleted_at"),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_customers_org").on(table.orgId),
    index("idx_customers_org_name").on(table.orgId, table.lastName, table.firstName),
    index("idx_customers_org_phone").on(table.orgId, table.phone),
    index("idx_customers_org_email").on(table.orgId, table.email),
  ],
);

// ---- 3.3.4: leads ----
export const leads = sqliteTable(
  "leads",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    customerId: uuid("customer_id").references(() => customers.id),
    contactName: text("contact_name"),
    contactPhone: text("contact_phone"),
    contactEmail: text("contact_email"),
    source: text("source").notNull().default("phone_call"),
    sourceDetail: text("source_detail"),
    stage: text("stage").notNull().default("new"),
    priority: integer("priority").default(0),
    title: text("title"),
    description: text("description"),
    serviceType: text("service_type"),
    estimatedValue: money("estimated_value"),
    assignedTo: uuid("assigned_to").references(() => users.id),
    convertedToJobId: uuid("converted_to_job_id"),
    lostReason: text("lost_reason"),
    tags: jsonCol<string[]>("tags", []),
    customFields: jsonCol<Record<string, unknown>>("custom_fields", {}),
    dealSize: money("deal_size"),
    nextFollowUp: ts("next_follow_up"),
    aiScore: integer("ai_score"),
    aiScoreBreakdown: jsonCol<Record<string, unknown> | null>("ai_score_breakdown", null as unknown as Record<string, unknown>),
    aiAnalysis: text("ai_analysis"),
    aiCategory: text("ai_category"),
    aiActions: jsonCol<unknown[] | null>("ai_actions", null as unknown as unknown[]),
    deletedAt: ts("deleted_at"),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_leads_org").on(table.orgId),
    index("idx_leads_org_stage").on(table.orgId, table.stage),
    index("idx_leads_assigned").on(table.assignedTo),
    index("idx_leads_customer").on(table.customerId),
  ],
);

// ---- 3.3.5: lead_activities ----
export const leadActivities = sqliteTable(
  "lead_activities",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }),
    userId: uuid("user_id").references(() => users.id),
    activityType: text("activity_type").notNull(),
    description: text("description"),
    metadata: jsonCol<Record<string, unknown>>("metadata", {}),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_lead_activities_lead").on(table.leadId, table.createdAt),
    index("idx_lead_activities_org").on(table.orgId),
  ],
);

// ---- 3.3.6: conversations ----
export const conversations = sqliteTable(
  "conversations",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    customerId: uuid("customer_id").references(() => customers.id),
    leadId: uuid("lead_id").references(() => leads.id),
    channel: text("channel").notNull(),
    externalId: text("external_id"),
    subject: text("subject"),
    status: text("status").default("active"),
    assignedTo: uuid("assigned_to").references(() => users.id),
    isAiHandled: bool("is_ai_handled").default(false),
    aiEscalated: bool("ai_escalated").default(false),
    escalationReason: text("escalation_reason"),
    lastMessageAt: ts("last_message_at"),
    messageCount: integer("message_count").default(0),
    metadata: jsonCol<Record<string, unknown>>("metadata", {}),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_conversations_org").on(table.orgId),
    index("idx_conversations_customer").on(table.customerId),
    index("idx_conversations_external").on(table.externalId),
    index("idx_conversations_org_channel").on(table.orgId, table.channel),
  ],
);

// ---- 3.3.7: messages ----
export const messages = sqliteTable(
  "messages",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    conversationId: uuid("conversation_id").notNull().references(() => conversations.id, { onDelete: "cascade" }),
    role: text("role").notNull(),
    senderId: uuid("sender_id").references(() => users.id),
    content: text("content").notNull(),
    contentHtml: text("content_html"),
    attachments: jsonCol<unknown[]>("attachments", []),
    metadata: jsonCol<Record<string, unknown>>("metadata", {}),
    twilioSid: text("twilio_sid"),
    readAt: ts("read_at"),
    deliveredAt: ts("delivered_at"),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_messages_conversation").on(table.conversationId, table.createdAt),
    index("idx_messages_org").on(table.orgId),
  ],
);

// ---- 3.3.8: calls ----
export const calls = sqliteTable(
  "calls",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    conversationId: uuid("conversation_id").references(() => conversations.id),
    leadId: uuid("lead_id").references(() => leads.id),
    customerId: uuid("customer_id").references(() => customers.id),
    twilioCallSid: text("twilio_call_sid").unique(),
    fromNumber: text("from_number").notNull(),
    toNumber: text("to_number").notNull(),
    direction: text("direction").notNull(),
    status: text("status").notNull(),
    duration: integer("duration"),
    recordingUrl: text("recording_url"),
    transcription: text("transcription"),
    summary: text("summary"),
    sentiment: text("sentiment"),
    intent: text("intent"),
    aiHandled: bool("ai_handled").default(false),
    aiHandoffAt: ts("ai_handoff_at"),
    startedAt: ts("started_at"),
    endedAt: ts("ended_at"),
    metadata: jsonCol<Record<string, unknown>>("metadata", {}),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_calls_org").on(table.orgId),
    index("idx_calls_org_timestamp").on(table.orgId, table.startedAt),
    index("idx_calls_customer").on(table.customerId),
    index("idx_calls_lead").on(table.leadId),
  ],
);

// ---- 3.3.9: appointments ----
export const appointments = sqliteTable(
  "appointments",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    customerId: uuid("customer_id").notNull().references(() => customers.id),
    leadId: uuid("lead_id").references(() => leads.id),
    jobId: uuid("job_id"),
    title: text("title").notNull(),
    description: text("description"),
    status: text("status").notNull().default("scheduled"),
    scheduledStart: ts("scheduled_start").notNull(),
    scheduledEnd: ts("scheduled_end").notNull(),
    actualStart: ts("actual_start"),
    actualEnd: ts("actual_end"),
    timezone: text("timezone").notNull(),
    assignedTechnicians: jsonCol<string[]>("assigned_technicians", []),
    addressLine1: text("address_line1"),
    addressLine2: text("address_line2"),
    city: text("city"),
    state: text("state"),
    postalCode: text("postal_code"),
    latitude: real("latitude"),
    longitude: real("longitude"),
    notes: text("notes"),
    isAllDay: bool("is_all_day").default(false),
    recurrenceRule: text("recurrence_rule"),
    googleEventId: text("google_event_id"),
    reminderSentAt: ts("reminder_sent_at"),
    confirmationSentAt: ts("confirmation_sent_at"),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_appointments_org").on(table.orgId),
    index("idx_appointments_org_range").on(table.orgId, table.scheduledStart, table.scheduledEnd),
    index("idx_appointments_customer").on(table.customerId),
    index("idx_appointments_job").on(table.jobId),
  ],
);

// ---- 3.3.10: technicians ----
export const technicians = sqliteTable(
  "technicians",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    userId: uuid("user_id").references(() => users.id),
    firstName: text("first_name").notNull(),
    lastName: text("last_name").notNull(),
    email: text("email"),
    phone: text("phone"),
    employeeId: text("employee_id"),
    title: text("title"),
    skills: jsonCol<string[]>("skills", []),
    serviceArea: jsonCol<Record<string, unknown>>("service_area", {}),
    hourlyRate: money("hourly_rate"),
    isActive: bool("is_active").default(true),
    color: text("color"),
    maxJobsPerDay: integer("max_jobs_per_day").default(8),
    workSchedule: jsonCol<Record<string, unknown>>("work_schedule", {}),
    googleCalendarId: text("google_calendar_id"),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_technicians_org").on(table.orgId),
    index("idx_technicians_user").on(table.userId),
  ],
);

// ---- 3.3.11: quotes ----
export const quotes = sqliteTable(
  "quotes",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    number: text("number").notNull(),
    leadId: uuid("lead_id").references(() => leads.id),
    customerId: uuid("customer_id").notNull().references(() => customers.id),
    jobId: uuid("job_id"),
    status: text("status").notNull().default("draft"),
    title: text("title").notNull(),
    description: text("description"),
    subtotal: money("subtotal").notNull(),
    discountAmount: money("discount_amount").default(0),
    discountPercent: money("discount_percent").default(0),
    taxRate: money("tax_rate").default(0),
    taxAmount: money("tax_amount").default(0),
    total: money("total").notNull(),
    currency: text("currency").default("USD"),
    validUntil: ts("valid_until"),
    terms: text("terms"),
    pdfUrl: text("pdf_url"),
    sentAt: ts("sent_at"),
    viewedAt: ts("viewed_at"),
    acceptedAt: ts("accepted_at"),
    declinedAt: ts("declined_at"),
    createdBy: uuid("created_by").notNull().references(() => users.id),
    deletedAt: ts("deleted_at"),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    uniqueIndex("idx_quotes_org_number").on(table.orgId, table.number),
    index("idx_quotes_org").on(table.orgId),
    index("idx_quotes_org_status").on(table.orgId, table.status),
    index("idx_quotes_customer").on(table.customerId),
    index("idx_quotes_lead").on(table.leadId),
  ],
);

// ---- 3.3.12: quote_line_items ----
export const quoteLineItems = sqliteTable(
  "quote_line_items",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    quoteId: uuid("quote_id").notNull().references(() => quotes.id, { onDelete: "cascade" }),
    description: text("description").notNull(),
    quantity: money("quantity").notNull().default(1),
    unit: text("unit").default("ea"),
    unitPrice: money("unit_price").notNull(),
    total: money("total").notNull(),
    isLabor: bool("is_labor").default(false),
    sortOrder: integer("sort_order").default(0),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_quote_items_quote").on(table.quoteId),
    index("idx_quote_items_org").on(table.orgId),
  ],
);

// ---- 3.3.13: jobs ----
export const jobs = sqliteTable(
  "jobs",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    number: text("number").notNull(),
    customerId: uuid("customer_id").notNull().references(() => customers.id),
    leadId: uuid("lead_id").references(() => leads.id),
    quoteId: uuid("quote_id").references(() => quotes.id),
    invoiceId: uuid("invoice_id"),
    title: text("title").notNull(),
    description: text("description"),
    status: text("status").notNull().default("new"),
    priority: integer("priority").default(0),
    serviceType: text("service_type"),
    scheduledStart: ts("scheduled_start"),
    scheduledEnd: ts("scheduled_end"),
    actualStart: ts("actual_start"),
    actualEnd: ts("actual_end"),
    assignedTechs: jsonCol<string[]>("assigned_techs", []),
    addressLine1: text("address_line1"),
    addressLine2: text("address_line2"),
    city: text("city"),
    state: text("state"),
    postalCode: text("postal_code"),
    latitude: real("latitude"),
    longitude: real("longitude"),
    estimatedHours: money("estimated_hours"),
    actualHours: money("actual_hours"),
    notes: text("notes"),
    internalNotes: text("internal_notes"),
    tags: jsonCol<string[]>("tags", []),
    customFields: jsonCol<Record<string, unknown>>("custom_fields", {}),
    completedAt: ts("completed_at"),
    cancelledAt: ts("cancelled_at"),
    cancelReason: text("cancel_reason"),
    deletedAt: ts("deleted_at"),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    uniqueIndex("idx_jobs_org_number").on(table.orgId, table.number),
    index("idx_jobs_org").on(table.orgId),
    index("idx_jobs_org_status").on(table.orgId, table.status),
    index("idx_jobs_customer").on(table.customerId),
    index("idx_jobs_org_scheduled").on(table.orgId, table.scheduledStart),
  ],
);

// ---- 3.3.14: job_activities ----
export const jobActivities = sqliteTable(
  "job_activities",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    jobId: uuid("job_id").notNull().references(() => jobs.id, { onDelete: "cascade" }),
    userId: uuid("user_id").references(() => users.id),
    activityType: text("activity_type").notNull(),
    description: text("description"),
    metadata: jsonCol<Record<string, unknown>>("metadata", {}),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_job_activities_job").on(table.jobId, table.createdAt),
    index("idx_job_activities_org").on(table.orgId),
  ],
);

// ---- 3.3.15: job_photos ----
export const jobPhotos = sqliteTable(
  "job_photos",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    jobId: uuid("job_id").notNull().references(() => jobs.id, { onDelete: "cascade" }),
    userId: uuid("user_id").references(() => users.id),
    url: text("url").notNull(),
    thumbnailUrl: text("thumbnail_url"),
    caption: text("caption"),
    takenAt: ts("taken_at"),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_job_photos_job").on(table.jobId),
    index("idx_job_photos_org").on(table.orgId),
  ],
);

// ---- 3.3.16: invoices ----
export const invoices = sqliteTable(
  "invoices",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    number: text("number").notNull(),
    customerId: uuid("customer_id").notNull().references(() => customers.id),
    jobId: uuid("job_id").references(() => jobs.id),
    quoteId: uuid("quote_id").references(() => quotes.id),
    status: text("status").notNull().default("draft"),
    subtotal: money("subtotal").notNull(),
    discountAmount: money("discount_amount").default(0),
    taxRate: money("tax_rate").default(0),
    taxAmount: money("tax_amount").default(0),
    total: money("total").notNull(),
    amountPaid: money("amount_paid").default(0),
    balanceDue: money("balance_due"),
    currency: text("currency").default("USD"),
    dueDate: ts("due_date"),
    issuedAt: ts("issued_at"),
    paidAt: ts("paid_at"),
    lastPaymentAt: ts("last_payment_at"),
    notes: text("notes"),
    terms: text("terms"),
    pdfUrl: text("pdf_url"),
    stripeInvoiceId: text("stripe_invoice_id"),
    stripePaymentIntentId: text("stripe_payment_intent_id"),
    sentAt: ts("sent_at"),
    deletedAt: ts("deleted_at"),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    uniqueIndex("idx_invoices_org_number").on(table.orgId, table.number),
    index("idx_invoices_org").on(table.orgId),
    index("idx_invoices_org_status").on(table.orgId, table.status),
    index("idx_invoices_customer").on(table.customerId),
    index("idx_invoices_job").on(table.jobId),
  ],
);

// ---- 3.3.17: invoice_line_items ----
export const invoiceLineItems = sqliteTable(
  "invoice_line_items",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    invoiceId: uuid("invoice_id").notNull().references(() => invoices.id, { onDelete: "cascade" }),
    description: text("description").notNull(),
    quantity: money("quantity").notNull().default(1),
    unit: text("unit").default("ea"),
    unitPrice: money("unit_price").notNull(),
    total: money("total").notNull(),
    sortOrder: integer("sort_order").default(0),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_invoice_items_invoice").on(table.invoiceId),
    index("idx_invoice_items_org").on(table.orgId),
  ],
);

// ---- 3.3.18: payments ----
export const payments = sqliteTable(
  "payments",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    invoiceId: uuid("invoice_id").notNull().references(() => invoices.id),
    customerId: uuid("customer_id").notNull().references(() => customers.id),
    amount: money("amount").notNull(),
    method: text("method").notNull(),
    transactionId: text("transaction_id"),
    receiptUrl: text("receipt_url"),
    status: text("status").notNull().default("completed"),
    notes: text("notes"),
    paidAt: ts("paid_at").notNull(),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_payments_invoice").on(table.invoiceId),
    index("idx_payments_org").on(table.orgId),
    index("idx_payments_customer").on(table.customerId),
  ],
);

// ---- 3.3.19: reviews ----
export const reviews = sqliteTable(
  "reviews",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    customerId: uuid("customer_id").notNull().references(() => customers.id),
    jobId: uuid("job_id").references(() => jobs.id),
    rating: integer("rating").notNull(),
    title: text("title"),
    body: text("body"),
    response: text("response"),
    respondedAt: ts("responded_at"),
    source: text("source").default("sitepilot"),
    externalUrl: text("external_url"),
    isPublic: bool("is_public").default(true),
    isFeatured: bool("is_featured").default(false),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_reviews_org").on(table.orgId),
    index("idx_reviews_customer").on(table.customerId),
    index("idx_reviews_job").on(table.jobId),
  ],
);

// ---- 3.3.20: automations ----
export const automations = sqliteTable(
  "automations",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    name: text("name").notNull(),
    description: text("description"),
    trigger: text("trigger").notNull(),
    triggerConfig: jsonCol<Record<string, unknown>>("trigger_config", {}),
    conditions: jsonCol<unknown[]>("conditions", []),
    action: text("action").notNull(),
    actionConfig: jsonCol<Record<string, unknown>>("action_config", {}),
    isActive: bool("is_active").default(true),
    delayMinutes: integer("delay_minutes").default(0),
    lastTriggeredAt: ts("last_triggered_at"),
    runCount: integer("run_count").default(0),
    createdBy: uuid("created_by").references(() => users.id),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_automations_org").on(table.orgId),
    index("idx_automations_trigger").on(table.orgId, table.trigger),
  ],
);

// ---- 3.3.21: automation_runs ----
export const automationRuns = sqliteTable(
  "automation_runs",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    automationId: uuid("automation_id").notNull().references(() => automations.id, { onDelete: "cascade" }),
    status: text("status").notNull().default("pending"),
    triggerEntityType: text("trigger_entity_type").notNull(),
    triggerEntityId: uuid("trigger_entity_id").notNull(),
    result: jsonCol<Record<string, unknown>>("result", {}),
    errorMessage: text("error_message"),
    startedAt: ts("started_at"),
    completedAt: ts("completed_at"),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_automation_runs_org").on(table.orgId),
    index("idx_automation_runs_automation").on(table.automationId),
  ],
);

// ---- 3.3.22: ai_configurations ----
export const aiConfigurations = sqliteTable(
  "ai_configurations",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    name: text("name").notNull(),
    configType: text("config_type").notNull(),
    model: text("model").notNull().default("gpt-4o"),
    systemPrompt: text("system_prompt").notNull(),
    personality: jsonCol<Record<string, unknown>>("personality", {}),
    knowledgeBase: jsonCol<unknown[]>("knowledge_base", []),
    toolsEnabled: jsonCol<string[]>("tools_enabled", []),
    fallbackAction: text("fallback_action").default("escalate"),
    escalationRules: jsonCol<Record<string, unknown>>("escalation_rules", {}),
    voiceId: text("voice_id"),
    language: text("language").default("en"),
    maxTurns: integer("max_turns").default(20),
    isActive: bool("is_active").default(false),
    isDefault: bool("is_default").default(false),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_ai_configs_org").on(table.orgId),
    uniqueIndex("idx_ai_configs_org_type").on(table.orgId, table.configType),
  ],
);

// ---- 3.3.23: ai_knowledge_documents ----
export const aiKnowledgeDocuments = sqliteTable(
  "ai_knowledge_documents",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    aiConfigId: uuid("ai_config_id").references(() => aiConfigurations.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    content: text("content").notNull(),
    contentType: text("content_type").default("text"),
    metadata: jsonCol<Record<string, unknown>>("metadata", {}),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_ai_knowledge_org").on(table.orgId),
    index("idx_ai_knowledge_config").on(table.aiConfigId),
  ],
);

// ---- 3.3.24: subscriptions ----
export const subscriptions = sqliteTable(
  "subscriptions",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    stripeSubscriptionId: text("stripe_subscription_id").unique(),
    stripeCustomerId: text("stripe_customer_id"),
    planTier: text("plan_tier").notNull(),
    status: text("status").notNull().default("incomplete"),
    seats: integer("seats").notNull().default(1),
    unitPrice: money("unit_price").notNull(),
    totalPrice: money("total_price").notNull(),
    currency: text("currency").default("USD"),
    billingCycle: text("billing_cycle").default("monthly"),
    currentPeriodStart: ts("current_period_start"),
    currentPeriodEnd: ts("current_period_end"),
    trialEndsAt: ts("trial_ends_at"),
    cancelledAt: ts("cancelled_at"),
    cancelAtPeriodEnd: bool("cancel_at_period_end").default(false),
    paymentMethod: jsonCol<Record<string, unknown>>("payment_method", {}),
    metadata: jsonCol<Record<string, unknown>>("metadata", {}),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [
    index("idx_subscriptions_org").on(table.orgId),
    uniqueIndex("idx_subscriptions_org_active").on(table.orgId),
  ],
);

// ---- 3.3.25: usage_records ----
export const usageRecords = sqliteTable(
  "usage_records",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    subscriptionId: uuid("subscription_id").references(() => subscriptions.id),
    metric: text("metric").notNull(),
    quantity: money("quantity").notNull(),
    unit: text("unit").notNull(),
    recordedAt: ts("recorded_at").notNull(),
    periodStart: integer("period_start", { mode: "timestamp_ms" }).notNull(),
    periodEnd: integer("period_end", { mode: "timestamp_ms" }).notNull(),
    metadata: jsonCol<Record<string, unknown>>("metadata", {}),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_usage_org").on(table.orgId),
    index("idx_usage_org_period").on(table.orgId, table.periodStart, table.periodEnd),
    index("idx_usage_subscription").on(table.subscriptionId),
  ],
);

// ---- 3.3.26: analytics_events ----
export const analyticsEvents = sqliteTable(
  "analytics_events",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    userId: uuid("user_id").references(() => users.id),
    eventName: text("event_name").notNull(),
    eventCategory: text("event_category").notNull(),
    properties: jsonCol<Record<string, unknown>>("properties", {}),
    sessionId: text("session_id"),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_analytics_org_time").on(table.orgId, table.createdAt),
    index("idx_analytics_org_event").on(table.orgId, table.eventName, table.createdAt),
    index("idx_analytics_org_category").on(table.orgId, table.eventCategory, table.createdAt),
  ],
);

// ---- 3.3.27: audit_logs ----
export const auditLogs = sqliteTable(
  "audit_logs",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    userId: uuid("user_id").references(() => users.id),
    action: text("action").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id"),
    changes: jsonCol<Record<string, unknown>>("changes", {}),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    requestId: text("request_id"),
    metadata: jsonCol<Record<string, unknown>>("metadata", {}),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_audit_org").on(table.orgId),
    index("idx_audit_org_time").on(table.orgId, table.createdAt),
    index("idx_audit_entity").on(table.entityType, table.entityId),
    index("idx_audit_user").on(table.userId),
    index("idx_audit_action").on(table.orgId, table.action, table.createdAt),
  ],
);

// ---- 3.3.28: api_keys ----
export const apiKeys = sqliteTable(
  "api_keys",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    userId: uuid("user_id").references(() => users.id),
    name: text("name").notNull(),
    keyHash: text("key_hash").notNull(),
    keyPrefix: text("key_prefix").notNull(),
    scopes: jsonCol<string[]>("scopes", []),
    lastUsedAt: ts("last_used_at"),
    expiresAt: ts("expires_at"),
    isActive: bool("is_active").default(true),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_api_keys_org").on(table.orgId),
    uniqueIndex("idx_api_keys_hash").on(table.keyHash),
  ],
);

// ---- 3.3.29: notifications ----
export const notifications = sqliteTable(
  "notifications",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    userId: uuid("user_id").notNull().references(() => users.id),
    type: text("type").notNull(),
    title: text("title").notNull(),
    body: text("body"),
    isRead: bool("is_read").default(false),
    actionUrl: text("action_url"),
    entityType: text("entity_type"),
    entityId: uuid("entity_id"),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_notifications_user").on(table.userId, table.createdAt),
    index("idx_notifications_org").on(table.orgId),
    index("idx_notifications_user_unread").on(table.userId, table.isRead),
  ],
);

// ---- 3.3.30: webhook_endpoints ----
export const webhookEndpoints = sqliteTable(
  "webhook_endpoints",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    name: text("name").notNull(),
    url: text("url").notNull(),
    secret: text("secret").notNull(),
    events: jsonCol<string[]>("events", []),
    isActive: bool("is_active").default(true),
    lastSentAt: ts("last_sent_at"),
    failureCount: integer("failure_count").default(0),
    createdAt: tsNow("created_at"),
    updatedAt: tsNow("updated_at"),
  },
  (table) => [index("idx_webhooks_org").on(table.orgId)],
);

// ---- 3.3.31: webhook_deliveries ----
export const webhookDeliveries = sqliteTable(
  "webhook_deliveries",
  {
    id: uid(),
    orgId: uuid("org_id").notNull().references(() => organizations.id),
    endpointId: uuid("endpoint_id").notNull().references(() => webhookEndpoints.id, { onDelete: "cascade" }),
    event: text("event").notNull(),
    payload: jsonCol<Record<string, unknown>>("payload", {}),
    responseStatus: integer("response_status"),
    responseBody: text("response_body"),
    attemptCount: integer("attempt_count").default(1),
    status: text("status").default("pending"),
    deliveredAt: ts("delivered_at"),
    nextRetryAt: ts("next_retry_at"),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_webhook_deliveries_endpoint").on(table.endpointId),
    index("idx_webhook_deliveries_org").on(table.orgId),
    index("idx_webhook_deliveries_retry").on(table.status, table.nextRetryAt),
  ],
);

// ---- 3.3.32: refresh_tokens ----
export const refreshTokens = sqliteTable(
  "refresh_tokens",
  {
    id: uid(),
    userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
    token: text("token").notNull(),
    expiresAt: ts("expires_at").notNull(),
    revoked: bool("revoked").notNull().default(false),
    createdAt: tsNow("created_at"),
  },
  (table) => [
    index("idx_refresh_tokens_user").on(table.userId),
    index("idx_refresh_tokens_token").on(table.token),
  ],
);
